version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data_warehouse
      - POSTGRES_PORT=5432
    ports: 
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
     # Script para criar os dados de exemplo
      - ./dados/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql