version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=saque_voleio_erp
      - POSTGRES_PORT=5432
    ports: 
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data